# Generated by Django 3.0.7 on 2020-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='title',
            new_name='caucus',
        ),
        migrations.AddField(
            model_name='letter',
            name='chamber',
            field=models.CharField(default='Chamber default', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='consecutive_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='legislator',
            field=models.CharField(default='legislator default', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='link',
            field=models.URLField(default='default link', verbose_name='Link to letter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='party',
            field=models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent')], default='default party', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='rep_or_sen',
            field=models.CharField(choices=[('Rep.', 'Representative'), ('Sen.', 'Senator')], default='defauly rep sen', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='topic',
            field=models.CharField(default='default topic', max_length=25),
            preserve_default=False,
        ),
    ]
