# Generated by Django 3.0.7 on 2020-07-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0004_auto_20200730_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='code',
            field=models.CharField(default='Date.Chamber.Party.Topic', max_length=25),
        ),
    ]
