# Generated by Django 3.0.7 on 2020-07-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0006_remove_letter_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateField(),
        ),
    ]
