# Generated by Django 3.0.7 on 2020-07-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0008_auto_20200730_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='consecutive_number',
        ),
        migrations.AlterField(
            model_name='letter',
            name='chamber',
            field=models.CharField(choices=[('B', 'Bicameral'), ('S', 'Senado'), ('C', 'Congreso')], max_length=9),
        ),
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateTimeField(help_text='Enter dates in <em>MM/DD/YYYY</em> format'),
        ),
    ]
