# Generated by Django 3.0.7 on 2020-08-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0010_auto_20200804_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jurisdiction', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY'), ('DC', 'DC')], max_length=30)),
                ('rep_or_sen', models.CharField(choices=[('Rep.', 'Representative'), ('Sen.', 'Senator')], max_length=4, verbose_name='Representative or Senator')),
                ('party', models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent')], max_length=11)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='letter',
            name='author',
        ),
        migrations.AlterField(
            model_name='letter',
            name='MX_mentioned',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=3, verbose_name='Was Mexico directly mentioned?'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='comments',
            field=models.TextField(default='N/a'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='cosigners',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='letter',
            name='description',
            field=models.TextField(verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='kind_of_statement',
            field=models.CharField(choices=[('Carta', 'Carta'), ('Consulta', 'Consulta'), ('Declaración', 'Declaracion')], max_length=15),
        ),
        migrations.AlterField(
            model_name='letter',
            name='kind_statement_party',
            field=models.CharField(choices=[('Republicano', 'Republican'), ('Demócrata', 'Democrat'), ('Bipartidista', 'Bipartisan')], max_length=12),
        ),
        migrations.AlterField(
            model_name='letter',
            name='notice_num',
            field=models.CharField(default='N/a', max_length=30, verbose_name='If a notice was sent, specify the number'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='positive_MX',
            field=models.CharField(choices=[('1', 'Positive'), ('2', 'Neutral'), ('3', 'Negative')], max_length=8, verbose_name='Positive for Mexico?'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='recipient',
            field=models.CharField(max_length=50, verbose_name='Recipient(s)'),
        ),
    ]
