# Generated by Django 3.1 on 2020-08-17 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0012_remove_letter_kind_of_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='topic',
            new_name='tema',
        ),
    ]
