# Generated by Django 3.1 on 2020-08-17 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0013_auto_20200817_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='date',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='specific_topic',
            new_name='tema_específico',
        ),
    ]
