# Generated by Django 3.1 on 2020-08-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0014_auto_20200817_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='description',
            new_name='descripción',
        ),
    ]
