# Generated by Django 3.1 on 2020-08-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0017_auto_20200817_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='chamber',
            new_name='cámara',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='kind_statement_party',
            new_name='partido',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='legislator',
            new_name='patrocinador',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='party',
        ),
    ]
