# Generated by Django 3.1 on 2020-08-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0019_auto_20200817_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='mención_directa_a_MX',
            field=models.IntegerField(choices=[('1', 'Yes'), ('0', 'No')], max_length=3, verbose_name='Was Mexico directly mentioned?'),
        ),
    ]
