# Generated by Django 3.1 on 2020-08-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0022_auto_20200817_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter',
            old_name='legislatura',
            new_name='cosigners',
        ),
    ]
