# Generated by Django 3.1 on 2020-08-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0023_auto_20200817_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='partido',
        ),
    ]
