# Generated by Django 3.1 on 2020-08-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0025_auto_20200817_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caucus',
            options={'verbose_name_plural': 'Caucuses'},
        ),
        migrations.AddField(
            model_name='letter',
            name='legislatura',
            field=models.CharField(choices=[], default=116, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letter',
            name='acción',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='caucus',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='letter',
            name='destinatario',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='letter',
            name='tema',
            field=models.CharField(choices=[], max_length=25),
        ),
        migrations.AlterField(
            model_name='letter',
            name='tema_específico',
            field=models.CharField(choices=[], max_length=25),
        ),
    ]
