# Generated by Django 3.1 on 2020-08-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0027_auto_20200818_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='patrocinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letter_tracking.legislator'),
        ),
    ]
