# Generated by Django 3.1 on 2020-08-20 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0028_auto_20200818_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='cámara',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='rep_or_sen',
        ),
        migrations.AlterField(
            model_name='letter',
            name='caucus',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='letter',
            name='cosigners',
            field=models.CharField(max_length=500, verbose_name='Copatrocinador/a'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='descripción',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='letter',
            name='destinatario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='letter',
            name='legislatura',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='letter',
            name='mención_directa_a_MX',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=3, verbose_name='Was Mexico directly mentioned?'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='patrocinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letter_tracking.legislator', verbose_name='Patrocinador/a'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='tema',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='letter',
            name='tema_específico',
            field=models.TextField(),
        ),
    ]
