# Generated by Django 3.1 on 2020-08-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0030_auto_20200820_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caucus',
            name='caucus_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
