# Generated by Django 3.1 on 2020-08-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0031_auto_20200820_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caucus',
            name='caucus_name',
            field=models.CharField(default='Na', max_length=25),
        ),
    ]
