# Generated by Django 3.1 on 2020-08-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0033_auto_20200820_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislator',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='letter',
            name='cosigners',
        ),
        migrations.AddField(
            model_name='letter',
            name='cosigners',
            field=models.ManyToManyField(related_name='copatrocinador', to='letter_tracking.Legislator', verbose_name='Copatrocinador/a'),
        ),
    ]
