# Generated by Django 3.1 on 2020-08-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0034_auto_20200820_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legislator',
            options={},
        ),
        migrations.RemoveField(
            model_name='letter',
            name='cosigners',
        ),
        migrations.AddField(
            model_name='letter',
            name='cosigners',
            field=models.CharField(default='cosin default', max_length=500, verbose_name='Copatrocinador/a'),
            preserve_default=False,
        ),
    ]
