# Generated by Django 3.1 on 2020-08-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0036_auto_20200823_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='cosigners',
        ),
        migrations.AddField(
            model_name='letter',
            name='cosigners',
            field=models.CharField(default='default', max_length=500, verbose_name='Copatrocinador/a'),
            preserve_default=False,
        ),
    ]
