# Generated by Django 3.1 on 2020-08-23 22:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0037_auto_20200823_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='cosigners',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200, verbose_name='Copatrocinador/a'),
        ),
    ]
