# Generated by Django 3.1 on 2020-08-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0043_auto_20200824_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislator',
            name='name',
        ),
    ]
