# Generated by Django 3.1 on 2020-08-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0045_auto_20200824_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='last_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
