# Generated by Django 3.1 on 2020-08-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0046_auto_20200824_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legislator',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='legislator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='cosigners',
        ),
    ]
