# Generated by Django 3.1 on 2020-08-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0049_auto_20200824_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='patrocinador',
        ),
        migrations.AddField(
            model_name='letter',
            name='patrocinador_rep',
            field=models.ForeignKey(limit_choices_to={'rep_or_sen': 'Rep.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Representatives', to='letter_tracking.legislator', verbose_name='Senate Author'),
        ),
        migrations.AddField(
            model_name='letter',
            name='patrocinador_sen',
            field=models.ForeignKey(limit_choices_to={'rep_or_sen': 'Sen.'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Senators', to='letter_tracking.legislator', verbose_name='Senate Author'),
        ),
    ]
