# Generated by Django 3.1 on 2020-08-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0052_auto_20200825_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='caucus',
            field=models.ManyToManyField(blank=True, to='letter_tracking.Caucus'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='destinatario',
            field=models.ManyToManyField(blank=True, to='letter_tracking.Recipient'),
        ),
    ]
