# Generated by Django 3.1 on 2020-08-25 22:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0054_auto_20200825_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='caucus',
        ),
        migrations.AddField(
            model_name='letter',
            name='caucus',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', 'N/a')], max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='cosigners',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'N/a')], default='None', max_length=1000, verbose_name='Copatrocinador/a'),
        ),
        migrations.RemoveField(
            model_name='letter',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='letter',
            name='destinatario',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', 'N/a')], max_length=100),
        ),
    ]
