# Generated by Django 3.1 on 2020-08-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0059_auto_20200825_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='favorable_a_MX',
            field=models.CharField(choices=[('1.0', 'Positive'), ('2.0', 'Neutral'), ('3.0', 'Negative')], max_length=8, verbose_name='Positive for Mexico?'),
        ),
    ]
