# Generated by Django 3.1 on 2020-08-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0060_auto_20200826_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='party',
            field=models.CharField(choices=[('D', 'Demócrata'), ('R', 'Republicano'), ('I', 'Independiente')], max_length=11),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='rep_or_sen',
            field=models.CharField(choices=[('Rep.', 'Congresista'), ('Sen.', 'Senador')], max_length=4, verbose_name='Representative or Senator'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='favorable_a_MX',
            field=models.CharField(choices=[('Positiva', 'Positiva'), ('Neutral', 'Neutral'), ('Negativa', 'Negativa')], max_length=8, verbose_name='Positive for Mexico?'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='mención_directa_a_MX',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], max_length=3, verbose_name='Was Mexico directly mentioned?'),
        ),
    ]
