# Generated by Django 3.1 on 2020-08-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0063_auto_20200831_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislator',
            name='full_name',
        ),
        migrations.AddField(
            model_name='legislator',
            name='name',
            field=models.CharField(default='None', max_length=100, verbose_name='Full Name'),
        ),
    ]
