# Generated by Django 3.1 on 2020-09-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0066_auto_20200831_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='cosigners',
        ),
        migrations.AlterField(
            model_name='legislator',
            name='rep_or_sen',
            field=models.CharField(choices=[('Rep.', 'Representative'), ('Sen.', 'Senator')], max_length=4, verbose_name='Representative or Senator'),
        ),
    ]
