# Generated by Django 3.1 on 2020-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0068_letter_cosigners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='fecha',
            field=models.DateField(help_text='Enter dates in <em>MM/DD/YYYY</em> format'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='mención_directa_a_MX',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=3, verbose_name='Was Mexico directly mentioned?'),
        ),
    ]
