# Generated by Django 3.1 on 2020-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0069_auto_20200901_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='fecha',
            field=models.DateTimeField(help_text='Enter dates in <em>MM/DD/YYYY</em> format'),
        ),
    ]
