# Generated by Django 3.1 on 2020-09-01 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0072_auto_20200901_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('abbr', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='letter',
            name='cosigners',
        ),
        migrations.AlterField(
            model_name='legislator',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letter_tracking.specific_topic'),
        ),
    ]
