# Generated by Django 3.1 on 2020-09-01 18:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0073_auto_20200901_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='cosigners',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], default='None', max_length=1000, verbose_name='Copatrocinador/a'),
        ),
    ]
