# Generated by Django 3.1 on 2020-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0076_auto_20200901_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='favorable_a_MX',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], max_length=8, verbose_name='Positive for Mexico?'),
        ),
    ]
