# Generated by Django 3.1 on 2020-09-02 19:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0077_auto_20200902_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='destinatario',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('N/a', 'N/a'), ('ACA', 'ACA'), ('BOP', 'BOP'), ('CBP', 'CBP'), ('CDC', 'CDC'), ('CRCL', 'CRCL'), ('DHS', 'DHS'), ('DOD', 'DOD'), ('DOE', 'DOE'), ('DOJ', 'DOJ'), ('DOL', 'DOL'), ('DOS', 'DOS'), ('DOT', 'DOT'), ('EMBAMEX', 'EMBAMEX'), ('EOIR', 'EOIR'), ('FEMA', 'FEMA'), ('GAO', 'GAO'), ('GEO', 'GEO'), ('HHS', 'HHS'), ('House Appropiations Committee Leadership', 'House Appropiations Committee Leadership'), ('House Majority Leader', 'House Majority Leader'), ('House Minority Leader', 'House Minority Leader'), ('HUD', 'HUD'), ('ICE', 'ICE'), ('IG DHS', 'IG DHS'), ('OJJDP', 'OJJDP'), ('POTUS', 'POTUS'), ('Senate Appropiations Committee Leadership', 'Senate Appropiations Committee Leadership'), ('Senate Majority Leader', 'Senate Majority Leader'), ('Senate Minority Leader', 'Senate Minority Leader'), ('USAID', 'USAID'), ('USBA', 'USBA'), ('USCIS', 'USCIS'), ('USTR', 'USTR'), ('VPOTUS', 'VPOTUS')], default='None', help_text="<em>If 'Other', please specify in the text box below</em>", max_length=100),
        ),
    ]
