# Generated by Django 3.1 on 2020-09-02 20:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0078_auto_20200902_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='caucus',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'N/a')], default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='cosigners',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], default='None', max_length=1000, verbose_name='Copatrocinador/a'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='destinatario',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('N/a', 'N/a')], default='None', help_text="<em>If 'Other', please specify in the text box below</em>", max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='other_destinatario_comments',
            field=models.TextField(blank=True),
        ),
    ]
