# Generated by Django 3.1 on 2020-09-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0081_auto_20200904_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letter_tracking.topic', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='tema_específico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letter_tracking.specific_topic', verbose_name='Specific Topic'),
        ),
    ]
