# Generated by Django 3.1 on 2020-09-08 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0084_auto_20200908_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letter_tracking.topic', verbose_name='-Topic'),
        ),
    ]
