# Generated by Django 3.1 on 2020-09-12 22:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0091_auto_20200912_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='caucus',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'N/a')], default='N/a', max_length=100),
        ),
        migrations.AlterField(
            model_name='letter',
            name='cosigners',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('', 'N/a')], default='None', max_length=1000, verbose_name='Cosigner(s)'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='destinatario',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('N/a', 'N/a')], default='None', help_text="<em>If 'Other', please specify in the text box below</em>", max_length=100, verbose_name='Recipients'),
        ),
    ]
