# Generated by Django 3.1 on 2020-09-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0092_auto_20200912_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='destinatario',
        ),
    ]
