# Generated by Django 3.1 on 2020-09-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0093_remove_letter_destinatario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='caucus',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='cosigners',
        ),
    ]
