# Generated by Django 3.1 on 2020-09-12 23:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0094_auto_20200912_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='destinatario',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('N/a', 'N/a')], default='None', help_text="<em>If 'Other', please specify in the text box below</em>", max_length=100, verbose_name='Recipients'),
        ),
    ]
