# Generated by Django 3.1 on 2020-09-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter_tracking', '0096_auto_20200912_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='caucus',
            name='caucus_name',
            field=models.CharField(blank=True, default='Na', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legislature',
            name='legislature_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='recipient_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specific_topic',
            name='specific_topic_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=100),
        ),
    ]
